import React from 'react'
import { FaArrowLeft, FaCheckCircle, FaChartLine, FaShieldAlt, FaRocket, FaUsers, FaDatabase, FaCog } from 'react-icons/fa'
import { useNavigate } from 'react-router-dom'
import './CaseStudy.css'

const CaseStudy = () => {
    const navigate = useNavigate()

    const metrics = [
        { value: '70%', label: 'Revenue Leakage Reduction', icon: FaChartLine },
        { value: '85%', label: 'Compliance Improvement', icon: FaCheckCircle },
        { value: '60%', label: 'Faster Collection Cycle', icon: FaRocket },
        { value: '100%', label: 'Invoice Visibility', icon: FaDatabase }
    ]

    const challenges = [
        'Revenue Leakage: Many collecting agents underreported actual sales or failed to issue proper invoices, resulting in tax loss',
        'Lack of Transparency: The government couldn\'t track daily taxable transactions or verify if the declared tax matched real sales',
        'Manual Declaration: Reliance on paper or Excel-based self-reporting introduced errors and delays',
        'Non-Compliance by Small Vendors: Many small or low-margin businesses lacked digital tools to generate or record invoices',
        'Disparate Accounting Systems: Businesses used various platforms (Sage, Oracle, Microsoft Dynamics), making centralized integration difficult',
        'Audit Challenges: Without standardized data, auditing declarations was slow and reactive',
        'Low Public Confidence: Citizens couldn\'t verify whether the tax collected from them was legitimate or remitted to the government'
    ]

    const solutions = [
        {
            title: 'Automated Invoice Tracking',
            description: 'Captures every invoice generated by registered collecting agents through real-time API synchronization or upload channels.'
        },
        {
            title: 'AI-Driven Invoice Validation Engine',
            description: 'Each invoice is automatically analyzed to ensure the correct 5% consumption tax is applied. The AI engine recalculates the tax and compares it to the declared value with a tolerance threshold (±0.5%). Non-compliant invoices are automatically flagged.'
        },
        {
            title: 'Automated Government Tax Invoice Generation',
            description: 'At the end of each tax period, the system automatically generates official tax invoices to collecting agents, summarizing their total sales, tax due, and remittance schedule.'
        },
        {
            title: 'EFS Integration Layer',
            description: 'The Electronic Fiscalization System (EFS) acts as a bridge between the LIRS system and third-party systems like Sage, Oracle, and Microsoft Dynamics, enabling automatic retrieval of sales data.'
        },
        {
            title: 'Hierarchical User Access',
            description: 'Multi-level access control for State, Regional, Zonal, and Field Officers ensures each user can view data relevant to their jurisdiction, with complete audit trails and change logs.'
        },
        {
            title: 'Digital Payment Gateway',
            description: 'Businesses can remit collected consumption tax directly online or through banking integrations, enabling traceable and secure transactions.'
        },
        {
            title: 'Public Verification App',
            description: 'Customers can verify invoice authenticity through a mobile app, promoting transparency and compliance.'
        },
        {
            title: 'Analytics and Audit Dashboard',
            description: 'Real-time dashboards and AI insights monitor tax collection progress, compliance percentages, and potential anomalies for audit review.'
        }
    ]

    const comparisonData = [
        { aspect: 'Revenue Leakage', before: 'High, due to underreporting', after: 'Reduced via AI validation & real-time invoice capture', improvement: '↓ 70%' },
        { aspect: 'Compliance', before: 'Manual, inconsistent', after: 'Automated, verified at source', improvement: '↑ 85%' },
        { aspect: 'Tax Transparency', before: 'Limited visibility', after: 'Real-time invoice-level monitoring', improvement: '↑ 100%' },
        { aspect: 'Payment Efficiency', before: 'Manual remittance', after: 'Instant online payment gateway', improvement: '↑ 60%' },
        { aspect: 'Audit & Oversight', before: 'Reactive audits', after: 'AI-based proactive anomaly detection', improvement: '↓ 50% time' },
        { aspect: 'Public Trust', before: 'Low awareness', after: 'Customer invoice verification app', improvement: '↑ 40% confidence' }
    ]

    return (
        <div className="case-study">
            {/* Hero Section */}
            <section className="case-study-hero">
                <div className="case-study-container">
                    <button className="back-button" onClick={() => navigate('/')}>
                        <FaArrowLeft /> Back to Projects
                    </button>

                    <div className="hero-badge">
                        <FaRocket /> Success Story
                    </div>

                    <h1 className="hero-title">
                        Digital Transformation of the Lagos Internal Revenue Service (LIRS)
                        <span className="highlight"> Consumption Tax Automation System</span>
                    </h1>

                    <p className="hero-subtitle">
                        How AI-powered automation transformed tax compliance and eliminated 70% revenue leakage for Lagos State Government
                    </p>

                    <div className="hero-tags">
                        <span className="tag">FinTech</span>
                        <span className="tag">AI/ML</span>
                        <span className="tag">Compliance Automation</span>
                        <span className="tag">Government</span>
                        <span className="tag">Data Validation</span>
                    </div>
                </div>
            </section>

            {/* Metrics Section */}
            <section className="metrics-section">
                <div className="case-study-container">
                    <h2 className="section-title">Impact at a Glance</h2>
                    <div className="metrics-grid">
                        {metrics.map((metric, index) => (
                            <div key={index} className="metric-card">
                                <metric.icon className="metric-icon" />
                                <div className="metric-value">{metric.value}</div>
                                <div className="metric-label">{metric.label}</div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Client Background */}
            <section className="content-section">
                <div className="case-study-container">
                    <div className="content-header">
                        <FaUsers className="section-icon" />
                        <h2>Client Background</h2>
                    </div>
                    <div className="content-body">
                        <p>
                            The <strong>Lagos Internal Revenue Service (LIRS)</strong> is the official tax authority of the Lagos State Government, Nigeria.
                            It manages and enforces the collection of taxes across the state, including the 5% Consumption Tax applied to consumable goods
                            and services in restaurants, hotels, bars, lounges, and event centers.
                        </p>
                        <p>
                            As Lagos continues to expand its economic footprint, the government aimed to ensure full transparency, accountability, and
                            automation in how consumption tax is tracked, calculated, and remitted by businesses operating within the state.
                        </p>
                    </div>
                </div>
            </section>

            {/* Project Background */}
            <section className="content-section alt-bg">
                <div className="case-study-container">
                    <div className="content-header">
                        <FaDatabase className="section-icon" />
                        <h2>Project Background</h2>
                    </div>
                    <div className="content-body">
                        <p>
                            Previously, the consumption tax collection framework was based on a <strong>manual self-declaration model</strong> — businesses
                            (collecting agents) declared their monthly sales and remitted 5% tax voluntarily. This model lacked verification and data integrity,
                            leading to massive under-reporting, delayed payments, and revenue leakages.
                        </p>
                        <p>
                            To resolve this, LIRS launched the <strong>LIRS Consumption Tax Automation System</strong> — a centralized, intelligent digital
                            platform designed to:
                        </p>
                        <ul className="feature-list">
                            <li>Capture all sales invoices from registered collecting agents in real time</li>
                            <li>Automatically calculate and verify the applicable 5% consumption tax</li>
                            <li>Generate tax invoices on behalf of the government for each agent</li>
                            <li>Enable secure online or banking-based payment of collected taxes</li>
                            <li>Provide multi-level user access across state, regional, and zonal offices</li>
                            <li>Integrate with third-party ERP and POS systems through the Electronic Fiscalization System (EFS) layer</li>
                        </ul>
                        <p>
                            This initiative aimed to create an <strong>end-to-end auditable, transparent, and data-driven</strong> consumption tax management
                            ecosystem for Lagos State.
                        </p>
                    </div>
                </div>
            </section>

            {/* Challenges */}
            <section className="content-section">
                <div className="case-study-container">
                    <div className="content-header">
                        <FaShieldAlt className="section-icon" />
                        <h2>Challenges</h2>
                    </div>
                    <div className="content-body">
                        <p>
                            Before the LIRS Consumption Tax Automation System was implemented, LIRS faced major systemic and operational issues:
                        </p>
                        <div className="challenges-grid">
                            {challenges.map((challenge, index) => (
                                <div key={index} className="challenge-card">
                                    <div className="challenge-number">{index + 1}</div>
                                    <p>{challenge}</p>
                                </div>
                            ))}
                        </div>
                        <p className="highlight-text">
                            LIRS required a robust, AI-powered digital system to automatically track, calculate, and validate tax from each business in
                            real time, ensuring compliance and minimizing revenue leakage.
                        </p>
                    </div>
                </div>
            </section>

            {/* Solution */}
            <section className="content-section alt-bg">
                <div className="case-study-container">
                    <div className="content-header">
                        <FaCog className="section-icon" />
                        <h2>Solution</h2>
                    </div>
                    <div className="content-body">
                        <p>
                            To overcome these challenges, the <strong>LIRS Consumption Tax Automation System</strong> was developed — a comprehensive,
                            multi-tiered digital platform that automated the entire consumption tax lifecycle from sales to remittance.
                        </p>
                        <h3 className="subsection-title">Core Solution Components:</h3>
                        <div className="solutions-grid">
                            {solutions.map((solution, index) => (
                                <div key={index} className="solution-card">
                                    <div className="solution-header">
                                        <div className="solution-number">{index + 1}</div>
                                        <h4>{solution.title}</h4>
                                    </div>
                                    <p>{solution.description}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </section>

            {/* Benefits - Comparison Table */}
            <section className="content-section">
                <div className="case-study-container">
                    <div className="content-header">
                        <FaChartLine className="section-icon" />
                        <h2>Benefits & Impact</h2>
                    </div>
                    <div className="content-body">
                        <p>
                            The implementation of the LIRS Consumption Tax Automation System has transformed the Lagos State consumption tax ecosystem,
                            delivering both operational and financial improvements.
                        </p>
                        <div className="comparison-table">
                            <div className="table-header">
                                <div className="table-cell">Impact Area</div>
                                <div className="table-cell">Before Implementation</div>
                                <div className="table-cell">After Implementation</div>
                                <div className="table-cell">Improvement</div>
                            </div>
                            {comparisonData.map((row, index) => (
                                <div key={index} className="table-row">
                                    <div className="table-cell"><strong>{row.aspect}</strong></div>
                                    <div className="table-cell">{row.before}</div>
                                    <div className="table-cell">{row.after}</div>
                                    <div className="table-cell improvement">{row.improvement}</div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </section>

            {/* Conclusion */}
            <section className="content-section conclusion-section">
                <div className="case-study-container">
                    <div className="content-header">
                        <FaCheckCircle className="section-icon" />
                        <h2>Conclusion</h2>
                    </div>
                    <div className="content-body">
                        <p>
                            The <strong>LIRS Consumption Tax Automation System</strong> has redefined how Lagos State manages and enforces consumption tax compliance.
                            By introducing AI-based validation, multi-level audit controls, and integration with business systems via the EFS layer, the solution
                            established full transparency, accountability, and accuracy across the entire tax collection cycle.
                        </p>
                        <div className="conclusion-highlights">
                            <h3>With the system, the Lagos Government can now:</h3>
                            <ul className="feature-list">
                                <li>Monitor every sale and associated tax in real time</li>
                                <li>Automatically raise verified tax invoices</li>
                                <li>Enforce compliance across thousands of collecting agents</li>
                                <li>Empower citizens to verify their tax payments instantly</li>
                            </ul>
                        </div>
                        <p>
                            The AI-powered validation engine has proven instrumental in detecting discrepancies early, ensuring only compliant invoices proceed
                            to billing and remittance — thereby eliminating leakage and improving trust between the government, businesses, and citizens.
                        </p>
                        <p className="final-statement">
                            Today, the <strong>LIRS Consumption Tax Automation System</strong> stands as a model for digital tax governance, demonstrating how
                            smart automation and data integration can transform public revenue systems at scale.
                        </p>
                    </div>
                </div>
            </section>
        </div>
    )
}

export default CaseStudy
